import subprocess

# DraftIssue IDs (DI_ prefix), NOT ProjectV2Item IDs (PVTI_ prefix)
cards = {
    "epic1": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7I", "body": "## Contexto\n\nDurante o Product Discovery, identificou-se que o app nao possui nenhum sistema de crash reporting (L04). Firebase Crashlytics nunca foi configurado, o que torna erros de producao completamente invisiveis.\n\n## Por que e critico\n\nSem visibilidade de erros, nao e possivel priorizar correcoes por impacto real. O mantenedor opera cego.\n\n## Resolucao\n\nIntegrar Firebase Crashlytics ao projeto, configurar inicializacao no LouveApp, e adicionar reporting de erros nao-fatais nos servicos de sincronizacao."},
    "epic2": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7M", "body": "## Contexto\n\nO Product Discovery revelou que Favoritos.md esta desatualizado (L12). Foi criado como planejamento pre-implementacao e nunca revisado.\n\n## Por que importa\n\nDocumentacao enganosa custa tempo de onboarding e pode levar a decisoes equivocadas. Com bus factor 1, documentacao precisa e a principal ferramenta de continuidade.\n\n## Resolucao\n\nRevisar e reescrever Favoritos.md para refletir a implementacao real: DefaultFavoritesRepository como mediador entre DataStore local e Firestore remoto, com servicos de migracao e sync."},
    "epic3": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7Q", "body": "## Contexto\n\nO Product Discovery apontou que o usuario nao tem visibilidade do estado da sincronizacao (L08). Os servicos de sync sao background invisivel.\n\n## Por que importa\n\nA confianca do usuario e diretamente afetada pela transparencia. Sem indicador, o usuario pode fechar o app achando que dados estao salvos quando nao estao.\n\n## Resolucao\n\nCriar StateFlow de SyncStatus, expor para UI, adicionar indicador visual no TopAppBar com estados: Synced, Syncing, Offline, Error."},
    "epic4": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7U", "body": "## Contexto\n\nO evidence-baseline identificou violacoes de Clean Architecture (L11). AuthRepository importa AuthUiState do UI layer. DataMigrationService e BidirectionalSyncService importam DefaultTheme do UI.\n\n## Por que importa\n\nViolacoes bloqueiam KMP e dificultam testes unitarios puros. ADR-006 ja as registra para correcao.\n\n## Resolucao\n\nMover AuthUiState e AuthError para domain/model. Substituir referencias a DefaultTheme por constantes em domain (ThemeDefaults ja existe)."},
    "epic5": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7Y", "body": "## Contexto\n\nO projeto nao possui feature flags (L05). Cada feature e ativada para 100% dos usuarios no release, sem rollout gradual, kill switch, ou testes A/B.\n\n## Por que importa\n\nSem feature flags, uma funcionalidade problematica nao pode ser desativada remotamente. Rollback na Play Store leva horas.\n\n## Resolucao\n\nConfigurar Firebase Remote Config e criar wrapper FeatureFlag com fallback local e FeatureFlagKey enum com keys padronizadas."},
    "epic6": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7c", "body": "## Contexto\n\nA sincronizacao so ocorre quando o app esta aberto e ha mudanca de conectividade (L09). Nao ha worker periodico.\n\n## Por que importa\n\nDados do usuario podem ficar dessincronizados por horas sem que o usuario perceba.\n\n## Resolucao\n\nCriar PeriodicWorkRequest com WorkManager para sync periodico em background (6h flex 2h). Agendar na inicializacao do LouveApp de forma idempotente."},
    "epic7": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7g", "body": "## Contexto\n\nO projeto nao tem pipeline CI/CD automatizado (L03). Build, lint e testes rodam apenas localmente. Esta e a limitacao central que amplifica o risco de todas as outras.\n\n## Por que e critico\n\nSem CI, testes nao bloqueiam regression (L01), release continua manual (L06), E2E nao automatiza (L13). CI/CD e o no central de dependencias da Fase 2.\n\n## Resolucao\n\nWorkflows GitHub Actions: build check, lint check, unit test check em cada PR para develop e main."},
    "epic8": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7k", "body": "## Contexto\n\nCobertura de testes e proxima de zero (L01). Projeto comecou sem cultura de testes. 18 bugs arquiteturais do v1.1.0 nao foram detectados por testes.\n\n## Por que importa\n\nCada commit pode quebrar funcionalidade sem aviso. Testes sao a base para qualquer melhoria de qualidade.\n\n## Resolucao\n\nTestes unitarios para repositorios (HymnRepositoryImpl, DefaultFavoritesRepository, DefaultSettingsRepository), servicos de sync (DataMigrationService, BidirectionalSyncService), e ViewModels (HomeViewModel, HymnDetailViewModel, AuthViewModel)."},
    "epic9": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7o", "body": "## Contexto\n\n7 fluxos Maestro E2E existem mas rodam apenas manualmente (L13). Regression de fluxo passa despercebida ate teste manual.\n\n## Por que importa\n\nE2E tests sao a ultima barreira antes da producao. Sem automacao, fluxos criticos (splash, home, busca, detalhes, navegacao) ficam desprotegidos.\n\n## Resolucao\n\nWorkflow GitHub Actions com emulador Android executando Maestro flows. Nightly ou manual trigger."},
    "epic10": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7s", "body": "## Contexto\n\nProcesso de release totalmente manual (L06). Build, assinatura e upload dependem de maquina local e acesso humano ao Play Console.\n\n## Por que e critico\n\nKeystore e ponto unico de falha. Cada release e evento de risco. Amplifica bus factor = 1.\n\n## Resolucao\n\nPipeline GitHub Actions: build AAB signed, upload ao Google Play Console via Publisher API, criar GitHub Release. Keystore em cofre seguro."},
    "epic11": {"id": "DI_lAHOBn6SPs4BhJgizgLBN7w", "body": "## Contexto\n\nSincronizacao atual e sempre full-sync (L07). Merge union sobre conjuntos inteiros. Aceitavel hoje, mas nao escala com listas de culto e historico.\n\n## Por que importa\n\nFull-sync e ineficiente em banda e processamento. Conforme o app cresce em dados por usuario, nao escala.\n\n## Resolucao\n\nDiff tracking entre estado local e remoto. Migrar BidirectionalSyncService para logica incremental."},
    "epic12": {"id": "DI_lAHOBn6SPs4BhJgizgLBN70", "body": "## Contexto\n\nBus factor = 1 (L02). Lucas de Lima e o unico mantenedor. Keystore, acesso Play Console, e todo conhecimento concentrados em uma pessoa.\n\n## Por que importa\n\nSe o mantenedor ficar indisponivel, o projeto para completamente. Mitigacao tecnica reduz impacto mas nao elimina o risco estrutural.\n\n## Resolucao\n\nDocumentar recuperacao do keystore. Backup em cofre seguro. Guia de onboarding. CI/CD (Epic 7) e Release (Epic 10) sao as mitigacoes de maior impacto."},
    "epic13": {"id": "DI_lAHOBn6SPs4BhJgizgLBN74", "body": "## Contexto\n\nDiscoverScreen e placeholder vazio (L10). Uma das 4 abas principais sem conteudo util. Visao do produto (Pilar 3) preve descoberta de conteudo.\n\n## Por que importa\n\nOportunidade perdida de engajamento e descoberta de hinos.\n\n## Resolucao\n\nConteudo editorial curado: categorias de hinos, hinos em destaque, texto introdutorio. Solucao temporaria ate sistema de categorizacao."},
    "f01": {"id": "DI_lAHOBn6SPs4BhJgizgLBN78", "body": "## Contexto dentro do Epic\n\nO Epic 1 (Observabilidade) nasceu da constatacao de que o app opera cego em producao. Sem Crashlytics, erros sao invisiveis. Esta Feature e o primeiro passo: integrar o SDK e ver crashes chegarem.\n\n## Descricao tecnica\n\nAdicionar Firebase Crashlytics SDK ao projeto. Configurar inicializacao na classe LouveApp. Garantir que o SDK capture crashes desde o startup. Testar integracao com crash forcado em debug."},
    "f02": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8A", "body": "## Contexto dentro do Epic\n\nO Epic 2 (Higiene de Documentacao) existe porque Favoritos.md engana novos desenvolvedores. Esta Feature reescreve o documento para alinhar com a implementacao real.\n\n## Descricao tecnica\n\nReescrever Favoritos.md para refletir: DefaultFavoritesRepository como mediador, DataStoreLocalFavoritesRepository local, FirestoreUserRepositoryImpl remoto. Mencionar DataMigrationService e BidirectionalSyncService."},
    "f03": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8E", "body": "## Contexto dentro do Epic\n\nO Epic 3 (Feedback de Sincronizacao) resolve a invisibilidade do sync para o usuario. Esta Feature cria o pipeline de dados que alimenta o indicador visual.\n\n## Descricao tecnica\n\nAdicionar StateFlow<SyncStatus> no ConnectivityMonitorService. SyncStatus enum: Synced, Syncing, Offline, Error. Expor como StateFlow para UI consumir."},
    "f04": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8I", "body": "## Contexto dentro do Epic\n\nO Epic 4 (Clean Architecture Enforcement) corrige violacoes que bloqueiam KMP. Esta Feature ataca as duas violacoes principais registradas no ADR-006.\n\n## Descricao tecnica\n\nMover AuthUiState e AuthError de ui/common/state para domain/model. Atualizar todas as referencias. Substituir DefaultTheme.name por constantes em ThemeDefaults (domain) em DataMigrationService e BidirectionalSyncService."},
    "f05": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8M", "body": "## Contexto dentro do Epic\n\nO Epic 5 (Gestao de Funcionalidades) habilita rollout seguro e kill switch. Esta Feature configura a infraestrutura base de Remote Config.\n\n## Descricao tecnica\n\nIntegrar Firebase Remote Config SDK. Configurar fetch com minimo para modo offline. Criar FeatureFlagKey enum com keys padronizadas. Criar wrapper FeatureFlag(FeatureFlagKey): Boolean com cache local e valor default."},
    "f06": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8Q", "body": "## Contexto dentro do Epic\n\nO Epic 6 (Sincronizacao em Background) garante que dados sincronizem mesmo quando app esta fechado. Esta Feature implementa o worker periodico.\n\n## Descricao tecnica\n\nCriar PeriodicSyncWorker extendendo CoroutineWorker. Sync bidirecional. Periodo 6h flex 2h. Agendar em LouveApp.onCreate com enqueueUniquePeriodicWork para idempotencia."},
    "f07": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8U", "body": "## Contexto dentro do Epic\n\nO Epic 7 (Pipeline CI/CD) e o no central que desbloqueia toda a Fase 2. Esta Feature implementa o workflow basico de validacao de PR.\n\n## Descricao tecnica\n\nWorkflow GitHub Actions disparando em pull_request para develop e main. Jobs: build (assembleDebug), lint (detekt/ktlint), test (./gradlew test). Falha em qualquer job bloqueia merge."},
    "f08": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8Y", "body": "## Contexto dentro do Epic\n\nO Epic 8 (Cobertura de Testes) constroi a rede de seguranca. Esta Feature cobre as camadas de dados: repositories e servicos de sync.\n\n## Descricao tecnica\n\nTestes unitarios com MockK e Coroutines Test para: HymnRepositoryImpl, DefaultFavoritesRepository (mediator logic), DefaultSettingsRepository (mediation), DataMigrationService (migrate, merge, backup), BidirectionalSyncService (sync, conflicts, resolve)."},
    "f09": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8c", "body": "## Contexto dentro do Epic\n\nO Epic 8 (Cobertura de Testes) precisa de testes em todas as camadas. Esta Feature foca nos ViewModels.\n\n## Descricao tecnica\n\nTestes unitarios com MockK e Coroutines Test para: HomeViewModel (search filter, debounce, load), HymnDetailViewModel (setHymnId, toggleFavorite, font scale), AuthViewModel (initial state, signIn, signOut, rate limiting)."},
    "f10": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8g", "body": "## Contexto dentro do Epic\n\nO Epic 9 (Automacao E2E em CI) fecha o ciclo de qualidade. Esta Feature integra Maestro ao pipeline CI.\n\n## Descricao tecnica\n\nWorkflow GitHub Actions que sobe emulador Android, instala APK debug, executa flows Maestro criticos, reporta resultados. Nightly ou manual trigger."},
    "f11": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8k", "body": "## Contexto dentro do Epic\n\nO Epic 10 (Release Automatizado) elimina o risco do processo manual. Esta Feature constroi a pipeline completa.\n\n## Descricao tecnica\n\nWorkflow GitHub Actions: build AAB signed com keystore de GitHub Secrets, upload ao Google Play Console via Publisher API, criar GitHub Release. Disparar em tag push v*."},
    "f12": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8o", "body": "## Contexto dentro do Epic\n\nO Epic 11 (Eficiencia de Sincronizacao) prepara o sync para escala futura. Esta Feature substitui full-sync por incremental.\n\n## Descricao tecnica\n\nDiff tracking com timestamps de ultima modificacao. Sincronizar apenas records modificados. Migrar BidirectionalSyncService para incremental merge."},
    "f13": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8s", "body": "## Contexto dentro do Epic\n\nO Epic 12 (Mitigacao de Bus Factor) endereca o risco estrutural de unico mantenedor. Esta Feature protege o keystore.\n\n## Descricao tecnica\n\nDocumentar processo de recuperacao do keystore. Backup em cofre seguro (1Password ou GitHub Secrets). Validar que backup assina build de teste."},
    "f14": {"id": "DI_lAHOBn6SPs4BhJgizgLBN8w", "body": "## Contexto dentro do Epic\n\nO Epic 12 (Mitigacao de Bus Factor) precisa atrair novos contribuidores. Esta Feature cria a porta de entrada.\n\n## Descricao tecnica\n\nGuia completo de onboarding: setup JDK/Android SDK, clonar e compilar, testes, Maestro E2E, fluxo de contribuicao, arquitetura do projeto."},
    "f15": {"id": "DI_lAHOBn6SPs4BhJgizgLBN80", "body": "## Contexto dentro do Epic\n\nO Epic 13 (Conteudo da DiscoverScreen) preenche o placeholder. Esta Feature adiciona conteudo editorial minimo.\n\n## Descricao tecnica\n\nConteudo estatico curado: cards de categorias de hinos, hinos em destaque, texto introdutorio. Dados compilados em constantes Kotlin."},
    "us11": {"id": "DI_lAHOBn6SPs4BhJgizgLBN84", "body": "Adicionar implementation(platform(libs.firebase.crashlytics)) e implementation(libs.firebase.crashlytics.ktx) ao app/build.gradle.kts. Sincronizar projeto. Verificar compilacao bem-sucedida."},
    "us12": {"id": "DI_lAHOBn6SPs4BhJgizgLBN88", "body": "Em LouveApp.onCreate(), apos super.onCreate(), inicializar FirebaseCrashlytics. Configurar setCrashlyticsCollectionEnabled(true). Testar com recordException em debug e verificar chegada no console Firebase."},
    "us13": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9A", "body": "Em DataMigrationService, BidirectionalSyncService, ConnectivityMonitorService: envolver blocos try-catch com recordException(e). Categorizar erros por tipo. Nao substituir logging existente."},
    "us21": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9I", "body": "Substituir docs/Favoritos.md. Novo documento: DefaultFavoritesRepository, DataStoreLocalFavoritesRepository, FirestoreUserRepositoryImpl, DataMigrationService, BidirectionalSyncService, estrategias de merge. Remover planejamento pre-implementacao."},
    "us31": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9M", "body": "Em ConnectivityMonitorService: adicionar MutableStateFlow(SyncStatus.Synced) e syncStatus: StateFlow<SyncStatus>. SyncStatus enum: Synced, Syncing, Offline, Error. Atualizar nos callbacks de rede."},
    "us32": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9Q", "body": "Criar SyncIndicator: icone + cor por estado. Integrar no HomeTopAppBar. Consumir via collectAsState. Tooltip: Sincronizado, Sincronizando..., Offline, Erro de sincronizacao."},
    "us41": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9U", "body": "Mover AuthUiState.kt de ui/common/state/ para domain/model/. AuthUiState e AuthError sao Kotlin puro. Atualizar imports em AuthRepository, FirebaseAuthRepositoryImpl, AuthViewModel, telas."},
    "us42": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9Y", "body": "Em DataMigrationService e BidirectionalSyncService: substituir DefaultTheme.name por ThemeDefaults.THEME_NAME. ThemeDefaults ja existe em domain/model/. Logica de merge inalterada."},
    "us51": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9c", "body": "Adicionar implementation(libs.firebase.config.ktx). Em AppModule: @Provides FirebaseRemoteConfig.getInstance(). Em LouveApp.onCreate: fetch com minimumFetchInterval."},
    "us52": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9g", "body": "Criar FeatureFlagKey enum no domain. Criar FeatureFlagProvider @Singleton @Inject: isEnabled(key, default): Boolean. Ler RemoteConfig, se null retornar default. Cache em memoria com TTL."},
    "us61": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9k", "body": "Criar PeriodicSyncWorker : CoroutineWorker(). doWork(): chamar BidirectionalSyncService.syncRemoteToLocal() e DataMigrationService.migrateLocalDataToCloud() se pendente. Constraints: NetworkType.CONNECTED."},
    "us62": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9o", "body": "Em LouveApp.onCreate: WorkManager.enqueueUniquePeriodicWork(periodic_sync, KEEP, syncRequest). Envolver em try-catch. Verificar com dumpsys jobscheduler."},
    "us71": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9s", "body": "Workflow .github/workflows/pr-build.yaml em pull_request para develop/main. Steps: checkout, setup-java 17, setup-gradle, ./gradlew assembleDebug. Caching."},
    "us72": {"id": "DI_lAHOBn6SPs4BhJgizgLBN9w", "body": "Step adicional no workflow: ./gradlew detekt ou ktlintCheck. Configurar detekt com baseline para codigo legado. Falha bloqueia PR."},
    "us73": {"id": "DI_lAHOBn6SPs4BhJgizgLBN90", "body": "Step: ./gradlew test. Falha em qualquer teste -> check fail. Upload artifact de app/build/reports/tests/ para debugging."},
}

mutation = "mutation($did:ID!,$b:String){updateProjectV2DraftIssue(input:{draftIssueId:$did body:$b}){draftIssue{title}}}"

for key, card in cards.items():
    body = card["body"]
    result = subprocess.run(
        ["gh", "api", "graphql", "-f", f"query={mutation}", "-F", f"did={card['id']}", "-F", f"b={body}", "--jq", ".data.updateProjectV2DraftIssue.draftIssue.title"],
        capture_output=True, text=True, cwd=r"D:\Projetos\harness-agentic-sdlc-base\project\louve-mobile-app"
    )
    out = result.stdout.strip()
    if out:
        print(f"OK: {key}")
    else:
        print(f"FAIL: {key} - stderr: {result.stderr.strip()[:200]}")

print("Done.")