$m = 'mutation($did:ID!,$b:String){updateProjectV2DraftIssue(input:{draftIssueId:$did body:$b}){draftIssue{title}}}'

$updates = @(
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhrk"; body="## Contexto\n\nDurante o Product Discovery, identificou-se que o app nao possui nenhum sistema de crash reporting (L04). Firebase Crashlytics nunca foi configurado, o que torna erros de producao completamente invisiveis. Bugs que afetam usuarios reais podem passar semanas sem deteccao, degradando a experiencia silenciosamente.\n\n## Por que isso e critico\n\nSem visibilidade de erros, nao e possivel priorizar correcoes por impacto real. O mantenedor opera cego. Um crash que ocorre para 10% dos usuarios pode nunca ser descoberto.\n\n## Resolucao\n\nIntegrar Firebase Crashlytics ao projeto, configurar inicializacao no LouveApp, e adicionar reporting de erros nao-fatais nos servicos de sincronizacao."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhrs"; body="## Contexto\n\nO Product Discovery revelou que Favoritos.md esta desatualizado (L12). O documento foi criado como planejamento antes da implementacao do sistema hibrido de favoritos e nunca foi revisado. Novos desenvolvedores leem informacoes incorretas sobre a arquitetura real.\n\n## Por que isso importa\n\nDocumentacao enganosa custa tempo de onboarding e pode levar a decisoes equivocadas. Com bus factor = 1, documentacao precisa e a principal ferramenta de continuidade.\n\n## Resolucao\n\nRevisar e reescrever Favoritos.md para refletir a implementacao real: DefaultFavoritesRepository como mediador entre DataStore local e Firestore remoto, mais servicos de migracao e sync."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhr0"; body="## Contexto\n\nO Product Discovery apontou que o usuario nao tem visibilidade do estado da sincronizacao (L08). Os servicos de sync foram implementados como processo de background invisivel. O usuario nunca sabe se seus favoritos foram salvos na nuvem ou se houve falha.\n\n## Por que isso importa\n\nA confianca do usuario no app e diretamente afetada pela transparencia dos dados. Sem indicador, o usuario pode fechar o app achando que dados estao salvos quando nao estao.\n\n## Resolucao\n\nCriar StateFlow de SyncStatus no ConnectivityMonitorService, expor para a UI, e adicionar indicador visual no TopAppBar com estados: Synced, Syncing, Offline, Error."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhsA"; body="## Contexto\n\nO Product Discovery e o evidence-baseline identificaram violacoes de Clean Architecture (L11). AuthRepository.kt importa AuthUiState do UI layer. DataMigrationService e BidirectionalSyncService importam DefaultTheme do UI layer. Isso quebra a regra fundamental de que domain nao pode depender de Android/UI.\n\n## Por que isso importa\n\nEssas violacoes bloqueiam a evolucao para KMP (compartilhar domain com iOS) e dificultam testes unitarios puros. O ADR-006 ja registra essas violacoes para correcao.\n\n## Resolucao\n\nMover AuthUiState e AuthError para domain/model. Substituir referencias a DefaultTheme por constantes em domain (ThemeDefaults ja existe)."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhsE"; body="## Contexto\n\nO Product Discovery identificou que o projeto nao possui feature flags (L05). Cada nova funcionalidade e ativada para 100% dos usuarios no momento do release, sem capacidade de rollout gradual, kill switch, ou testes A/B.\n\n## Por que isso importa\n\nSem feature flags, uma funcionalidade problematica nao pode ser desativada remotamente. Rollback na Play Store leva horas. Isso torna o processo de release arriscado e inibidor de inovacao.\n\n## Resolucao\n\nConfigurar Firebase Remote Config e criar wrapper FeatureFlag que leia do Remote Config com fallback local. FeatureFlagKey enum com keys padronizadas."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhsQ"; body="## Contexto\n\nO Product Discovery revelou que a sincronizacao so ocorre quando o app esta aberto e ha mudanca de conectividade (L09). ConnectivityMonitorService usa NetworkCallback, mas nao ha worker periodico. Dispositivos que ficam online sem mudanca de rede podem atrasar a sincronizacao.\n\n## Por que isso importa\n\nDados do usuario podem ficar dessincronizados por horas ou dias sem que o usuario perceba. Para usuarios que confiam no app para favoritos e configuracoes, isso e uma falha de experiencia.\n\n## Resolucao\n\nCriar PeriodicWorkRequest com WorkManager para sync periodico em background (6h com flex 2h). Agendar na inicializacao do LouveApp de forma idempotente."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhsY"; body="## Contexto\n\nO Product Discovery identificou que o projeto nao tem pipeline CI/CD automatizado (L03). Build, lint e testes rodam apenas localmente. Nao ha validacao automatica de PRs. Erros de compilacao sao descobertos tarde. Esta e a limitacao central que amplifica o risco de todas as outras.\n\n## Por que isso e critico\n\nSem CI, testes nao bloqueiam regression (L01), release continua manual (L06), e E2E nao automatiza (L13). CI/CD e o no central de dependencias de toda a Fase 2.\n\n## Resolucao\n\nCriar workflows de GitHub Actions: build check, lint check, e unit test check em cada PR para develop e main."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhsk"; body="## Contexto\n\nO Product Discovery constatou que a cobertura de testes e proxima de zero (L01). O projeto comecou sem cultura de testes. A versao v1.2.0 adicionou 37 testes, mas ainda ha repositorios, servicos e ViewModels sem cobertura. Os 18 bugs arquiteturais corrigidos no v1.2.0 nao foram detectados por testes.\n\n## Por que isso importa\n\nCada novo commit pode quebrar funcionalidade sem aviso. Regression silenciosa mina a confianca para evoluir o codigo. Testes sao a base para qualquer melhoria de qualidade.\n\n## Resolucao\n\nEscrever testes unitarios para todas as implementacoes de repositorio (HymnRepositoryImpl, DefaultFavoritesRepository, DefaultSettingsRepository), servicos de sync (DataMigrationService, BidirectionalSyncService), e ViewModels (HomeViewModel, HymnDetailViewModel, AuthViewModel)."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhso"; body="## Contexto\n\nO Product Discovery identificou que os 7 fluxos Maestro E2E existem mas so rodam manualmente via script PowerShell (L13). Sem automacao em CI, a execucao depende da iniciativa do desenvolvedor. Regression de fluxo passa despercebida ate teste manual.\n\n## Por que isso importa\n\nE2E tests sao a ultima barreira antes da producao. Sem automacao, o custo de execucao e alto e a frequencia baixa. Fluxos criticos (splash, home, busca, detalhes, favoritos, navegacao) ficam desprotegidos.\n\n## Resolucao\n\nConfigurar workflow de GitHub Actions para executar Maestro flows em emulador Android. Pode ser pipeline noturna ou manual trigger, nao necessariamente bloqueante em PR devido ao custo do emulador."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhs0"; body="## Contexto\n\nO Product Discovery revelou que o processo de release e totalmente manual (L06). O mantenedor executa ./gradlew assembleRelease localmente, assina com keystore em maquina local, e faz upload manual no Google Play Console. O keystore e o unico ponto de falha para atualizacoes.\n\n## Por que isso e critico\n\nSem keystore, nao ha atualizacao na Play Store. O processo depende de uma maquina especifica e de acesso humano ao Play Console. Isso amplifica o bus factor = 1 e torna cada release um evento de risco.\n\n## Resolucao\n\nCriar pipeline GitHub Actions que builda AAB assinado, faz upload ao Google Play Console via Publisher API, e cria GitHub Release. Keystore armazenado em cofre seguro."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhtE"; body="## Contexto\n\nO Product Discovery apontou que a sincronizacao atual e sempre full-sync (L07). Os servicos de sync fazem merge union sobre conjuntos inteiros. Para o volume atual de dados (favoritos, tema) isso e aceitavel, mas cresce em risco com novas features como listas de culto e historico.\n\n## Por que isso importa\n\nFull-sync e ineficiente em banda e processamento. Conforme o app cresce em dados por usuario (listas de culto, anotacoes, historico de visualizacao), essa abordagem nao escala. A documentacao ja registra sync incremental como proximo passo.\n\n## Resolucao\n\nImplementar diff tracking entre estado local e remoto para sincronizar apenas mudancas. Migrar BidirectionalSyncService para logica incremental. Complementar com WorkManager (Epic 6)."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhto"; body="## Contexto\n\nO Product Discovery identificou que o projeto tem bus factor = 1 (L02). Lucas de Lima e o unico mantenedor. Keystore, acesso ao Play Console, e todo conhecimento de operacao concentrados em uma pessoa. Esta e uma limitacao estrutural que nao se resolve apenas com codigo.\n\n## Por que isso importa\n\nSe o mantenedor ficar indisponivel, o projeto para completamente: sem releases, sem correcoes de bugs criticos, sem resposta a issues. A mitigacao tecnica (CI/CD, keystore backup) reduz o impacto mas nao elimina o risco.\n\n## Resolucao\n\nDocumentar processo de recuperacao do keystore. Fazer backup do keystore em cofre seguro. Criar guia completo de onboarding para novos contribuidores. CI/CD (Epic 7) e Release automatizado (Epic 10) sao as mitigacoes tecnicas de maior impacto."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhtw"; body="## Contexto\n\nO Product Discovery revelou que a tela Descubra (DiscoverScreen) e um placeholder vazio (L10). Uma das 4 abas principais da navegacao nao tem conteudo util. O usuario que clica em Descubra ve apenas cards informativos sobre funcionalidades futuras que nunca foram implementadas.\n\n## Por que isso importa\n\nQuatro abas na navegacao, uma delas sem proposito. Oportunidade perdida de engajamento e descoberta de hinos. A visao do produto (Pilar 3) preve que esta tela seja o centro de descoberta de conteudo.\n\n## Resolucao\n\nPreencher a DiscoverScreen com conteudo editorial curado: categorias de hinos, hinos em destaque, e conteudo introdutorio. Esta e uma solucao temporaria ate que o sistema de categorizacao (fora do escopo de Limitations) seja implementado."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhww"; body="## Contexto dentro do Epic\n\nO Epic 1 (Observabilidade) nasceu da constatacao de que o app opera cego em producao. Sem Crashlytics, erros sao invisiveis. Esta Feature e o primeiro passo: integrar o SDK e ver crashes chegarem.\n\n## Descricao tecnica\n\nAdicionar Firebase Crashlytics SDK ao projeto. Configurar inicializacao na classe LouveApp. Garantir que o SDK capture crashes desde o startup. Testar integracao com crash forcado em debug."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhw4"; body="## Contexto dentro do Epic\n\nO Epic 2 (Higiene de Documentacao) existe porque Favoritos.md engana novos desenvolvedores. Esta Feature reescreve o documento para alinhar com a implementacao real.\n\n## Descricao tecnica\n\nReescrever Favoritos.md para refletir: DefaultFavoritesRepository como mediador, DataStoreLocalFavoritesRepository para dados locais, FirestoreUserRepositoryImpl para dados remotos. Mencionar DataMigrationService e BidirectionalSyncService."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhxA"; body="## Contexto dentro do Epic\n\nO Epic 3 (Feedback de Sincronizacao) resolve a invisibilidade do sync para o usuario. Esta Feature cria o pipeline de dados que alimenta o indicador visual.\n\n## Descricao tecnica\n\nAdicionar StateFlow<SyncStatus> no ConnectivityMonitorService. SyncStatus enum: Synced, Syncing, Offline, Error. Expor como StateFlow para a UI consumir. Criar componente visual SyncIndicator para integracao no TopAppBar."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhxQ"; body="## Contexto dentro do Epic\n\nO Epic 4 (Clean Architecture Enforcement) corrige violacoes que bloqueiam KMP. Esta Feature ataca as duas violacoes principais registradas no ADR-006.\n\n\n## Descricao tecnica\n\nMover AuthUiState e AuthError de ui/common/state para domain/model. Atualizar todas as referencias (AuthRepository, ViewModels, telas). Substituir importacao de DefaultTheme.name em DataMigrationService e BidirectionalSyncService por constantes em ThemeDefaults (domain)."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhxY"; body="## Contexto dentro do Epic\n\nO Epic 5 (Gestao de Funcionalidades) habilita rollout seguro e kill switch. Esta Feature configura a infraestrutura base de Remote Config.\n\n## Descricao tecnica\n\nIntegrar Firebase Remote Config SDK. Configurar fetch com minimo para modo offline. Criar FeatureFlagKey enum com keys padronizadas. Criar wrapper FeatureFlag(FeatureFlagKey): Boolean com cache local da ultima resposta e valor default."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhxo"; body="## Contexto dentro do Epic\n\nO Epic 6 (Sincronizacao em Background) garante que dados sincronizem mesmo quando app esta fechado. Esta Feature implementa o worker periodico.\n\n## Descricao tecnica\n\nCriar PeriodicSyncWorker estendendo CoroutineWorker. Sync bidirecional entre local e remoto. Periodo: 6h (flex 2h) configuravel. Nao executar sem conectividade. Agendar em LouveApp.onCreate com WorkManager.enqueueUniquePeriodicWork para idempotencia."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhxw"; body="## Contexto dentro do Epic\n\nO Epic 7 (Pipeline CI/CD) e o no central que desbloqueia toda a Fase 2. Esta Feature implementa o workflow basico de validacao de PR.\n\n## Descricao tecnica\n\nWorkflow GitHub Actions disparando em pull_request para develop e main. Tres jobs: build (./gradlew assembleDebug), lint (detekt ou ktlint), test (./gradlew test). Falha em qualquer job bloqueia o merge. Relatorio de testes como artifact."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhyA"; body="## Contexto dentro do Epic\n\nO Epic 8 (Cobertura de Testes) constroi a rede de seguranca para evolucao segura. Esta Feature cobre as camadas de dados: repositories e servicos de sync.\n\n## Descricao tecnica\n\nTestes unitarios com MockK e Coroutines Test para: HymnRepositoryImpl (getAll, getById), DefaultFavoritesRepository (add, remove, getFavorites, mediator logic), DefaultSettingsRepository (theme/font mediation), DataMigrationService (migrateLocalToCloud, merge, backup), BidirectionalSyncService (syncRemoteToLocal, hasConflicts, resolveConflicts)."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhyI"; body="## Contexto dentro do Epic\n\nO Epic 8 (Cobertura de Testes) precisa de testes em todas as camadas. Esta Feature foca nos ViewModels que orquestram a logica de apresentacao.\n\n## Descricao tecnica\n\nTestes unitarios com MockK e Coroutines Test para: HomeViewModel (search filter, debounce, load hymns), HymnDetailViewModel (setHymnId, toggleFavorite optimistic update, font scale), AuthViewModel (initial state idle, signIn delegation, signOut delegation, rate limiting)."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhyY"; body="## Contexto dentro do Epic\n\nO Epic 9 (Automacao E2E em CI) fecha o ciclo de qualidade com testes de fluxo completos. Esta Feature integra o Maestro ao pipeline CI.\n\n## Descricao tecnica\n\nWorkflow GitHub Actions que sobe emulador Android, instala APK de debug, executa flows Maestro criticos, e reporta resultados. Pode ser nightly ou manual trigger. Usar maestro-action ou workflow customizado. Relatorio JUnit salvo como artifact."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhyk"; body="## Contexto dentro do Epic\n\nO Epic 10 (Release Automatizado) elimina o risco do processo manual. Esta Feature constroi a pipeline de release completa.\n\n## Descricao tecnica\n\nWorkflow GitHub Actions com tres stages: (1) build AAB signed com keystore de GitHub Secrets, (2) upload para Google Play Console via google-play-publisher-helper ou fastlane, (3) criar GitHub Release com changelog. Disparar em tag push v*."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhys"; body="## Contexto dentro do Epic\n\nO Epic 11 (Eficiencia de Sincronizacao) prepara o sync para escala futura. Esta Feature substitui full-sync por sincronizacao incremental.\n\n## Descricao tecnica\n\nImplementar diff tracking entre estado local e remoto. Manter timestamps de ultima modificacao para cada conjunto de dados (favorites, settings). Sincronizar apenas records modificados apos o ultimo sync. Migrar BidirectionalSyncService de union logic para incremental merge. Compatibilidade com WorkManager (Epic 6)."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhzA"; body="## Contexto dentro do Epic\n\nO Epic 12 (Mitigacao de Bus Factor) endereca o risco estrutural de ter um unico mantenedor. Esta Feature protege o ativo mais critico: o keystore.\n\n## Descricao tecnica\n\nDocumentar processo completo de recuperacao do keystore: onde esta armazenado, quem tem acesso, como recriar se perdido, como registrar nova chave na Play Store. Fazer backup do keystore em cofre seguro (1Password ou GitHub Secrets encrypted). Validar que o backup pode ser usado para assinar um build de teste."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhzI"; body="## Contexto dentro do Epic\n\nO Epic 12 (Mitigacao de Bus Factor) tambem precisa atrair e capacitar novos contribuidores. Esta Feature cria a porta de entrada para quem quiser ajudar.\n\n## Descricao tecnica\n\nCriar guia completo de onboarding: setup de ambiente (JDK, Android SDK, emulador), clonar e compilar, executar testes, executar Maestro E2E, fluxo de contribuicao (branch, commit, PR), arquitetura do projeto (camadas, pacotes), e referencias a documentacao existente."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jhzQ"; body="## Contexto dentro do Epic\n\nO Epic 13 (Conteudo da DiscoverScreen) preenche o placeholder da tela Descubra. Esta Feature adiciona conteudo editorial minimo para tornar a aba util.\n\n\n## Descricao tecnica\n\nAdicionar conteudo estatico curado a DiscoverScreen: categorias de hinos listadas em cards, hinos em destaque (selecionados manualmente), e texto introdutorio sobre a Harpa Crista. Dados compilados em constantes Kotlin (similar ao HymnDataSource). Nao requer API, cache, ou sincronizacao."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh1o"; body="## Descricao tecnica\n\nAdicionar `implementation(platform(libs.firebase.crashlytics))` e `implementation(libs.firebase.crashlytics.ktx)` ao app/build.gradle.kts. Sincronizar projeto. Verificar compilacao bem-sucedida."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh14"; body="## Descricao tecnica\n\nEm LouveApp.onCreate(), apos super.onCreate(), inicializar FirebaseCrashlytics. Configurar `setCrashlyticsCollectionEnabled(true)`. Testar com `FirebaseCrashlytics.getInstance().recordException(Exception(\"Test crash\"))` em debug e verificar chegada no console do Firebase."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh2E"; body="## Descricao tecnica\n\nEm DataMigrationService, envolver blocos try-catch com `FirebaseCrashlytics.getInstance().recordException(e)`. Mesmo para BidirectionalSyncService e ConnectivityMonitorService. Categorizar erros por tipo (network, auth, data). Nao substituir logging existente, apenas adicionar crashlytics como complemento."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh2c"; body="## Descricao tecnica\n\nSubstituir conteudo de docs/Favoritos.md. Novo documento deve descrever: DefaultFavoritesRepository como mediador entre DataStore local e Firestore remoto, logica de delegacao baseada em estado de login, DataMigrationService para migracao pos-login, BidirectionalSyncService para sync bidirecional, estrategias de merge (union para favoritos, preferencia local para tema). Remover referencias a planejamento nao implementado."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh2o"; body="## Descricao tecnica\n\nEm ConnectivityMonitorService, adicionar `private val _syncStatus = MutableStateFlow(SyncStatus.Synced)` e `val syncStatus: StateFlow<SyncStatus>`. SyncStatus enum: Synced, Syncing, Offline, Error. Atualizar _syncStatus nos pontos: onAvailable, onLost, onCapabilitiesChanged, quando sync comeca e termina. Usar `asStateFlow()` para exposicao."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh20"; body="## Descricao tecnica\n\nCriar componente SyncIndicator: Row com icone (check/sync/cloud-off/alert) e cor correspondente. Integrar no HomeTopAppBar, ao lado do botao de perfil. Consumir ConnectivityMonitorService.syncStatus via collectAsState. Tooltip com texto: Sincronizado, Sincronizando..., Offline, Erro de sincronizacao."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh28"; body="## Descricao tecnica\n\nMover arquivo AuthUiState.kt de ui/common/state/ para domain/model/. AuthUiState e AuthError estao em Kotlin puro (sem dependencias Android), a movimentacao e segura. Atualizar imports em: AuthRepository.kt (domain), FirebaseAuthRepositoryImpl.kt (data), AuthViewModel.kt (ui), SettingsScreen.kt (ui), ProfileScreen.kt (ui). Verificar compilacao."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh3Y"; body="## Descricao tecnica\n\nEm DataMigrationService, substituir `DefaultTheme.name` por `ThemeDefaults.THEME_NAME`. Em BidirectionalSyncService, mesma substituicao. Verificar que a logica de merge permanece identica (preferir tema personalizado sobre padrao). ThemeDefaults ja existe em domain/model/. Remover imports de ui/theme/AppThemes se existirem."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh3g"; body="## Descricao tecnica\n\nAdicionar `implementation(libs.firebase.config.ktx)` ao build.gradle.kts. Em AppModule (di/), adicionar @Provides para FirebaseRemoteConfig.getInstance(). Em LouveApp.onCreate(), configurar fetch com minimumFetchIntervalInSeconds para desenvolvimento. Criar wrapper FeatureFlag(FeatureFlagKey) que leia RemoteConfig ou retorne default se offline."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh3o"; body="## Descricao tecnica\n\nCriar FeatureFlagKey enum no domain: `enum class FeatureFlagKey(val key: String) { HABILITAR_CATEGORIZACAO(\"habilitar_categorizacao\"), ... }`. Criar FeatureFlagProvider @Singleton @Inject: `fun isEnabled(key: FeatureFlagKey, default: Boolean = false): Boolean`. Internamente: ler do RemoteConfig, se null ou exception retornar default. Cache em memoria com TTL."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh4A"; body="## Descricao tecnica\n\nCriar PeriodicSyncWorker : CoroutineWorker(). No doWork(): chamar BidirectionalSyncService.syncRemoteToLocal() e DataMigrationService.migrateLocalDataToCloud() se pendente. Constraints: NetworkType.CONNECTED. Periodo: PeriodicWorkRequestBuilder<PeriodicSyncWorker>(6, TimeUnit.HOURS). Adicionar flexInterval 2h."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh4Y"; body="## Descricao tecnica\n\nEm LouveApp.onCreate(), apos inicializar Hilt: `WorkManager.getInstance(this).enqueueUniquePeriodicWork(\"periodic_sync\", ExistingPeriodicWorkPolicy.KEEP, syncRequest)`. syncRequest e o PeriodicWorkRequest criado na US 6.1. Envolver em try-catch para nao travar startup. Verificar com adb shell dumpsys jobscheduler."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh4k"; body="## Descricao tecnica\n\nWorkflow em .github/workflows/pr-build.yaml. Trigger: pull_request para develop e main. Job: ubuntu-latest, steps: checkout, setup-java 17, setup-gradle, run ./gradlew assembleDebug. Usar gradle-build-action para caching. Nao falhar em warning, apenas erro."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh4o"; body="## Descricao tecnica\n\nWorkflow em .github/workflows/pr-lint.yaml ou mesmo workflow do build. Step adicional: run ./gradlew detekt ou ktlintCheck. Configurar ferramenta de lint (detekt recomendado) com baseline para codigo legado. Falha no lint bloqueia o PR."}
  @{id="PVTI_lAHOBn6SPs4BhJgizg4jh4w"; body="## Descricao tecnica\n\nWorkflow em .github/workflows/pr-test.yaml. Step: run ./gradlew test. Falha em qualquer teste -> saida != 0 -> check fail. Relatorio: upload-artifact de app/build/reports/tests/ para debugging. Pode ser combinado no mesmo workflow dos outros checks."}
)

$mutationBody = 'mutation($did:ID!,$b:String){updateProjectV2DraftIssue(input:{draftIssueId:$did body:$b}){draftIssue{title}}}'

foreach ($u in $updates) {
  $result = gh api graphql -f query="$mutationBody" -F did="$($u.id)" -F b="$($u.body)" --jq ".data.updateProjectV2DraftIssue.draftIssue.title" 2>&1
  Write-Host "Updated: $result"
}

Write-Host "`nAll descriptions updated successfully."